-- Phantom Breaker: Battlegrounds (USA)
-- Credits: Slade

needs_crc32 = false

cur_chts = {
	{["name"]="Mikoto Max Level", ["offset"]=0x44, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Mikoto Min Current Upgrade Points", ["offset"]=0x48, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Mikoto Max Upgrade", ["offset"]=0x4C, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Mikoto Max Attack", ["offset"]=0x60, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Mikoto Max Defense", ["offset"]=0x61, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Mikoto Max Speed", ["offset"]=0x62, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Mikoto Dash Attack", ["offset"]=0x50, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Hi Jump", ["offset"]=0x51, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Double Jump", ["offset"]=0x52, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto SP Attack Level 1", ["offset"]=0x53, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Air Throw", ["offset"]=0x54, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Counter Burst", ["offset"]=0x55, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Combo Level 1", ["offset"]=0x56, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto SP Attack Level 2", ["offset"]=0x57, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto GD Cancel", ["offset"]=0x58, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Counter Burst Level 2", ["offset"]=0x59, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Combo Level 2", ["offset"]=0x5A, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Ex Attack", ["offset"]=0x5B, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Critical Burst", ["offset"]=0x5C, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Over Drive Level 1", ["offset"]=0x5D, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Phantom Break", ["offset"]=0x5E, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Over Drive Level 2", ["offset"]=0x5F, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Max Level", ["offset"]=0x68, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Waka Min Current Upgrade Points", ["offset"]=0x6C, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Waka Max Upgrade", ["offset"]=0x70, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Waka Max Attack", ["offset"]=0x84, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Waka Max Defense", ["offset"]=0x85, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Waka Max Speed", ["offset"]=0x86, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Waka Dash Attack", ["offset"]=0x74, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Hi Jump", ["offset"]=0x75, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Double Jump", ["offset"]=0x76, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka SP Attack Level 1", ["offset"]=0x77, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Air Throw", ["offset"]=0x78, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Counter Burst", ["offset"]=0x79, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Combo Level 1", ["offset"]=0x7A, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka SP Attack Level 2", ["offset"]=0x7B, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka GD Cancel", ["offset"]=0x7C, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Counter Burst Level 2", ["offset"]=0x7D, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Combo Level 2", ["offset"]=0x7E, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Ex Attack", ["offset"]=0x7F, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Critical Burst", ["offset"]=0x80, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Over Drive Level 1", ["offset"]=0x81, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Phantom Break", ["offset"]=0x82, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Over Drive Level 2", ["offset"]=0x83, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Max Level", ["offset"]=0x8C, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Itsuki Min Current Upgrade Points", ["offset"]=0x90, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Itsuki Max Upgrade", ["offset"]=0x94, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Itsuki Max Attack", ["offset"]=0xA8, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Itsuki Max Defense", ["offset"]=0xA9, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Itsuki Max Speed", ["offset"]=0xAA, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Itsuki Dash Attack", ["offset"]=0x98, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Hi Jump", ["offset"]=0x99, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Double Jump", ["offset"]=0x9A, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki SP Attack Level 1", ["offset"]=0x9B, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Air Throw", ["offset"]=0x9C, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Counter Burst", ["offset"]=0x9D, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Combo Level 1", ["offset"]=0x9E, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki SP Attack Level 2", ["offset"]=0x9F, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki GD Cancel", ["offset"]=0xA0, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Counter Burst Level 2", ["offset"]=0xA1, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Combo Level 2", ["offset"]=0xA2, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Ex Attack", ["offset"]=0xA3, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Critical Burst", ["offset"]=0xA4, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Over Drive Level 1", ["offset"]=0xA5, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Phantom Break", ["offset"]=0xA6, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Over Drive Level 2", ["offset"]=0xA7, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Max Level", ["offset"]=0xB0, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Yuhuza Max Attack", ["offset"]=0xCC, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Yuhuza Min Current Upgrade Points", ["offset"]=0xB4, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Yuhuza Max Upgrade", ["offset"]=0xB8, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Yuhuza Max Defense", ["offset"]=0xCD, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Yuhuza Max Speed", ["offset"]=0xCE, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Yuhuza Dash Attack", ["offset"]=0xBC, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Hi Jump", ["offset"]=0xBD, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Double Jump", ["offset"]=0xBE, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza SP Attack Level 1", ["offset"]=0xBF, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Air Throw", ["offset"]=0xC0, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Counter Burst", ["offset"]=0xC1, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Combo Level 1", ["offset"]=0xC2, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza SP Attack Level 2", ["offset"]=0xC3, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza GD Cancel", ["offset"]=0xC4, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Counter Burst Level 2", ["offset"]=0xC5, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Combo Level 2", ["offset"]=0xC6, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Ex Attack", ["offset"]=0xC7, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Critical Burst", ["offset"]=0xC8, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Over Drive Level 1", ["offset"]=0xC9, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Phantom Break", ["offset"]=0xCA, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Over Drive Level 2", ["offset"]=0xCB, ["file"]="config.dat", ["value"]=0x02, ["size"]=1}
}