-- Phantom Breaker: Battlegrounds (USA)
-- Credits: Slade

needs_crc32 = false

warning = "In order to fully use the cheats, you must use the 'Min Current Upgrade Points' for the character you want to edit."

cur_chts = {
	{["name"]="Mikoto Max Level", ["offsets"]={0x44}, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Mikoto Min Current Upgrade Points", ["offsets"]={0x48}, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Mikoto Max Upgrade", ["offsets"]={0x4C}, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Mikoto Max Attack", ["offsets"]={0x60}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Mikoto Max Defense", ["offsets"]={0x61}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Mikoto Max Speed", ["offsets"]={0x62}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Mikoto Dash Attack", ["offsets"]={0x50}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Hi Jump", ["offsets"]={0x51}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Double Jump", ["offsets"]={0x52}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto SP Attack Level 1", ["offsets"]={0x53}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Air Throw", ["offsets"]={0x54}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Counter Burst", ["offsets"]={0x55}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Combo Level 1", ["offsets"]={0x56}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto SP Attack Level 2", ["offsets"]={0x57}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto GD Cancel", ["offsets"]={0x58}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Counter Burst Level 2", ["offsets"]={0x59}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Combo Level 2", ["offsets"]={0x5A}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Ex Attack", ["offsets"]={0x5B}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Critical Burst", ["offsets"]={0x5C}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Over Drive Level 1", ["offsets"]={0x5D}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Phantom Break", ["offsets"]={0x5E}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Mikoto Over Drive Level 2", ["offsets"]={0x5F}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Max Level", ["offsets"]={0x68}, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Waka Min Current Upgrade Points", ["offsets"]={0x6C}, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Waka Max Upgrade", ["offsets"]={0x70}, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Waka Max Attack", ["offsets"]={0x84}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Waka Max Defense", ["offsets"]={0x85}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Waka Max Speed", ["offsets"]={0x86}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Waka Dash Attack", ["offsets"]={0x74}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Hi Jump", ["offsets"]={0x75}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Double Jump", ["offsets"]={0x76}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka SP Attack Level 1", ["offsets"]={0x77}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Air Throw", ["offsets"]={0x78}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Counter Burst", ["offsets"]={0x79}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Combo Level 1", ["offsets"]={0x7A}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka SP Attack Level 2", ["offsets"]={0x7B}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka GD Cancel", ["offsets"]={0x7C}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Counter Burst Level 2", ["offsets"]={0x7D}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Combo Level 2", ["offsets"]={0x7E}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Ex Attack", ["offsets"]={0x7F}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Critical Burst", ["offsets"]={0x80}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Over Drive Level 1", ["offsets"]={0x81}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Phantom Break", ["offsets"]={0x82}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Waka Over Drive Level 2", ["offsets"]={0x83}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Max Level", ["offsets"]={0x8C}, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Itsuki Min Current Upgrade Points", ["offsets"]={0x90}, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Itsuki Max Upgrade", ["offsets"]={0x94}, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Itsuki Max Attack", ["offsets"]={0xA8}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Itsuki Max Defense", ["offsets"]={0xA9}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Itsuki Max Speed", ["offsets"]={0xAA}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Itsuki Dash Attack", ["offsets"]={0x98}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Hi Jump", ["offsets"]={0x99}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Double Jump", ["offsets"]={0x9A}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki SP Attack Level 1", ["offsets"]={0x9B}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Air Throw", ["offsets"]={0x9C}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Counter Burst", ["offsets"]={0x9D}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Combo Level 1", ["offsets"]={0x9E}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki SP Attack Level 2", ["offsets"]={0x9F}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki GD Cancel", ["offsets"]={0xA0}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Counter Burst Level 2", ["offsets"]={0xA1}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Combo Level 2", ["offsets"]={0xA2}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Ex Attack", ["offsets"]={0xA3}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Critical Burst", ["offsets"]={0xA4}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Over Drive Level 1", ["offsets"]={0xA5}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Phantom Break", ["offsets"]={0xA6}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Itsuki Over Drive Level 2", ["offsets"]={0xA7}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Max Level", ["offsets"]={0xB0}, ["file"]="config.dat", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Yuhuza Max Attack", ["offsets"]={0xCC}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Yuhuza Min Current Upgrade Points", ["offsets"]={0xB4}, ["file"]="config.dat", ["value"]=0x01, ["size"]=1},
	{["name"]="Yuhuza Max Upgrade", ["offsets"]={0xB8}, ["file"]="config.dat", ["value"]=0xFA, ["size"]=1},
	{["name"]="Yuhuza Max Defense", ["offsets"]={0xCD}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Yuhuza Max Speed", ["offsets"]={0xCE}, ["file"]="config.dat", ["value"]=0x0A, ["size"]=1},
	{["name"]="Yuhuza Dash Attack", ["offsets"]={0xBC}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Hi Jump", ["offsets"]={0xBD}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Double Jump", ["offsets"]={0xBE}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza SP Attack Level 1", ["offsets"]={0xBF}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Air Throw", ["offsets"]={0xC0}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Counter Burst", ["offsets"]={0xC1}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Combo Level 1", ["offsets"]={0xC2}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza SP Attack Level 2", ["offsets"]={0xC3}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza GD Cancel", ["offsets"]={0xC4}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Counter Burst Level 2", ["offsets"]={0xC5}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Combo Level 2", ["offsets"]={0xC6}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Ex Attack", ["offsets"]={0xC7}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Critical Burst", ["offsets"]={0xC8}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Over Drive Level 1", ["offsets"]={0xC9}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Phantom Break", ["offsets"]={0xCA}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1},
	{["name"]="Yuhuza Over Drive Level 2", ["offsets"]={0xCB}, ["file"]="config.dat", ["value"]=0x02, ["size"]=1}
}