-- Dead Nation (AUS)
-- Credits: Slade

needs_crc32 = false

warning = "Unlock cheats will make an item visible, but not purchasable. Both halves of the cheats will need to be run for two part cheats to enable them correctly."

cur_chts = {
	{["name"]="9,999,999 Cash", ["offsets"]={0x6A47}, ["file"]="SAVE.DAT", ["value"]=0x98967F, ["size"]=4},
	{["name"]="Max Rifle", ["offsets"]={0x6A8B}, ["file"]="SAVE.DAT", ["value"]=0x040404, ["size"]=4},
	{["name"]="SMG Unlock (No purchase)", ["offsets"]={0x6AA7}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="SMG Purchasable 1/2", ["offsets"]={0x6AB3}, ["file"]="SAVE.DAT", ["value"]=0x09090909, ["size"]=4},
	{["name"]="SMG Purchasable 2/2", ["offsets"]={0x6AB7}, ["file"]="SAVE.DAT", ["value"]=0x01, ["size"]=1},
	{["name"]="SMG Max Level 1/2", ["offsets"]={0x6AAB}, ["file"]="SAVE.DAT", ["value"]=0x09090909, ["size"]=4},
	{["name"]="SMG Max Level 2/2", ["offsets"]={0x6AAF}, ["file"]="SAVE.DAT", ["value"]=0x01, ["size"]=1},
	{["name"]="SMG Infinite Ammo", ["offsets"]={0x6ABD}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Shotgun Unlock (No Purchase)", ["offsets"]={0x6AC7}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Shotgun Purchasable 1/2", ["offsets"]={0x6AB3}, ["file"]="SAVE.DAT", ["value"]=0x09090909, ["size"]=4},
	{["name"]="Shotgun Purchasable 2/2", ["offsets"]={0x6AD7}, ["file"]="SAVE.DAT", ["value"]=0x01, ["size"]=1},
	{["name"]="Shotgun Max Level 1/2", ["offsets"]={0x6ACB}, ["file"]="SAVE.DAT", ["value"]=0x09090909, ["size"]=4},
	{["name"]="Shotgun Max Level 2/2", ["offsets"]={0x6ACF}, ["file"]="SAVE.DAT", ["value"]=0x01, ["size"]=1},
	{["name"]="Shotgun Infinite Ammo", ["offsets"]={0x6ADD}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Flamethrower Unlock (No purchase)", ["offsets"]={0x6AE7}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Flamethrower Purchasable", ["offsets"]={0x6AF3}, ["file"]="SAVE.DAT", ["value"]=0x04040404, ["size"]=4},
	{["name"]="Flamethrower Max Level", ["offsets"]={0x6AEB}, ["file"]="SAVE.DAT", ["value"]=0x04040404, ["size"]=4},
	{["name"]="Flamethrower Infinite Ammo", ["offsets"]={0x6AFD}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Blade Cannon Unlock (No purchase)", ["offsets"]={0x6B07}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Blade Cannon Purchasable", ["offsets"]={0x6B13}, ["file"]="SAVE.DAT", ["value"]=0xFF010202, ["size"]=4},
	{["name"]="Blade Cannon Max Level", ["offsets"]={0x6B0B}, ["file"]="SAVE.DAT", ["value"]=0xFF010202, ["size"]=4},
	{["name"]="Blade Cannon Infinite Ammo", ["offsets"]={0x6B1D}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Launcher Unlock (No purchase)", ["offsets"]={0x6B27}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Launcher Purchasable", ["offsets"]={0x6B33}, ["file"]="SAVE.DAT", ["value"]=0x0204, ["size"]=2},
	{["name"]="Launcher Max Level", ["offsets"]={0x6B2B}, ["file"]="SAVE.DAT", ["value"]=0x09090909, ["size"]=4},
	{["name"]="Launcher Infinite Ammo", ["offsets"]={0x6B3D}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Shocker Unlock (No purchase)", ["offsets"]={0x6B47}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Shocker Purchasable", ["offsets"]={0x6B53}, ["file"]="SAVE.DAT", ["value"]=0x04040404, ["size"]=4},
	{["name"]="Shocker Max Level", ["offsets"]={0x6B4B}, ["file"]="SAVE.DAT", ["value"]=0x04040404, ["size"]=4},
	{["name"]="Shocker Infinite Ammo", ["offsets"]={0x6B5D}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Flare Max Level", ["offsets"]={0x6B6B}, ["file"]="SAVE.DAT", ["value"]=0x0304, ["size"]=2},
	{["name"]="Flare Max Ammo", ["offsets"]={0x6B7D}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Grenade Max Level", ["offsets"]={0x6B8B}, ["file"]="SAVE.DAT", ["value"]=0x0304, ["size"]=2},
	{["name"]="Grenade Infinite Ammo", ["offsets"]={0x6B9D}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Mine Unlock (No purchase)", ["offsets"]={0x6BA7}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Mine Purchasable", ["offsets"]={0x6BB3}, ["file"]="SAVE.DAT", ["value"]=0x0304, ["size"]=2},
	{["name"]="Mine Max Level", ["offsets"]={0x6BAB}, ["file"]="SAVE.DAT", ["value"]=0x0304, ["size"]=2},
	{["name"]="Mine Infinite Ammo", ["offsets"]={0x6BBD}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Molotov Unlock (No purchase)", ["offsets"]={0x6BC7}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Molotov Purchasable", ["offsets"]={0x6BD3}, ["file"]="SAVE.DAT", ["value"]=0x02, ["size"]=1},
	{["name"]="Molotov Max Level", ["offsets"]={0x6BCB}, ["file"]="SAVE.DAT", ["value"]=0x02, ["size"]=1},
	{["name"]="Molotov Infinite Ammo", ["offsets"]={0x6BDD}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Dynamite Unlock (No purchase)", ["offsets"]={0x6BE7}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Dynamite Purchasable", ["offsets"]={0x6BF3}, ["file"]="SAVE.DAT", ["value"]=0x01, ["size"]=1},
	{["name"]="Dynamite Max Level", ["offsets"]={0x6BEB}, ["file"]="SAVE.DAT", ["value"]=0x01, ["size"]=1},
	{["name"]="Dynamite Infinite Ammo", ["offsets"]={0x6BFD}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2},
	{["name"]="Auto-Turret Unlock (No purchase)", ["offsets"]={0x6C07}, ["file"]="SAVE.DAT", ["value"]=0x03, ["size"]=1},
	{["name"]="Auto-Turret Purchasable", ["offsets"]={0x6C13}, ["file"]="SAVE.DAT", ["value"]=0x0303, ["size"]=2},
	{["name"]="Auto-Turret Max Level", ["offsets"]={0x6C0B}, ["file"]="SAVE.DAT", ["value"]=0x0303, ["size"]=2},
	{["name"]="Auto-Turret Infinite Ammo", ["offsets"]={0x6C1D}, ["file"]="SAVE.DAT", ["value"]=0xFFFF, ["size"]=2}
}
